/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFOODMENU,
    EntFOODMENUFromJSON,
    EntFOODMENUFromJSONTyped,
    EntFOODMENUToJSON,
    EntMainingre,
    EntMainingreFromJSON,
    EntMainingreFromJSONTyped,
    EntMainingreToJSON,
    EntSource,
    EntSourceFromJSON,
    EntSourceFromJSONTyped,
    EntSourceToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRecordfoodEdges
 */
export interface EntRecordfoodEdges {
    /**
     * 
     * @type {EntFOODMENU}
     * @memberof EntRecordfoodEdges
     */
    recordfoodmenu?: EntFOODMENU;
    /**
     * 
     * @type {EntMainingre}
     * @memberof EntRecordfoodEdges
     */
    recordingredient?: EntMainingre;
    /**
     * 
     * @type {EntSource}
     * @memberof EntRecordfoodEdges
     */
    recordsource?: EntSource;
    /**
     * 
     * @type {EntUser}
     * @memberof EntRecordfoodEdges
     */
    recorduser?: EntUser;
}

export function EntRecordfoodEdgesFromJSON(json: any): EntRecordfoodEdges {
    return EntRecordfoodEdgesFromJSONTyped(json, false);
}

export function EntRecordfoodEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRecordfoodEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordfoodmenu': !exists(json, 'RECORDFOODMENU') ? undefined : EntFOODMENUFromJSON(json['RECORDFOODMENU']),
        'recordingredient': !exists(json, 'RECORDINGREDIENT') ? undefined : EntMainingreFromJSON(json['RECORDINGREDIENT']),
        'recordsource': !exists(json, 'RECORDSOURCE') ? undefined : EntSourceFromJSON(json['RECORDSOURCE']),
        'recorduser': !exists(json, 'RECORDUSER') ? undefined : EntUserFromJSON(json['RECORDUSER']),
    };
}

export function EntRecordfoodEdgesToJSON(value?: EntRecordfoodEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recordfoodmenu': EntFOODMENUToJSON(value.recordfoodmenu),
        'recordingredient': EntMainingreToJSON(value.recordingredient),
        'recordsource': EntSourceToJSON(value.recordsource),
        'recorduser': EntUserToJSON(value.recorduser),
    };
}


